<?php

namespace SchoolBundle\Repository;

/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNomClasseByUser($userId)
    {


        $qb = $this
            ->createQueryBuilder('u')
            ->select('i.idClasse')
            ->from('SchoolBundle:Affectation', 'i')
            ->where('i.idProf =  :userId' )
            ->setParameter('userId', $userId)
        ;


        return $qb;
    }
}
