<?php

namespace BibliothequeBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    public function LivresLesPlusDemandes($biblio)
    {
        $query = $this->getEntityManager()->createQuery('select l, (select count(e.id) from BibliothequeBundle:Emprunt e where e.idlivre = l.id) as nbEmprunt from BibliothequeBundle:Livre l order by nbEmprunt')
        ->getMaxResults(5);
        /*$query = $this->getEntityManager()->createQuery('select l, (select count(e.id) from BibliothequeBundle:Emprunt e where e.idlivre = l.id) as nbEmprunt from BibliothequeBundle:Livre l where l.idBibliotheque = :biblio order by nbEmprunt')
            ->setParameter('biblio', $biblio)
            ->getMaxResults(5);*/
    }

    public function getAllCategorie(){
        $query = $this->getEntityManager()->createQuery('select distinct(l.categorie) from BibliothequeBundle:Livre l ');
        return $query->getResult();
    }
}
