<?php

namespace BibliothequeBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLivreLesPlusDemande(){
        //$qd = $this->getEntityManager()->createQuery('select l from BibliothequeBundle:Livre l order by l.');
    }
}
