bibliotheque:
    resource: "@BibliothequeBundle/Resources/config/routing.yml"
    prefix:   /bibliotheque

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

school:
    resource: "@SchoolBundle/Resources/config/routing.yml"
    prefix:   /school

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
