# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:

        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_Etudiant: ROLE_USER
        ROLE_Parent: ROLE_USER
        ROLE_Professeur: ROLE_USER
        ROLE_Scolarite: ROLE_USER
        ROLE_Bibliothecaire: ROLE_USER

        ROLE_MODERATOR: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path: /login
            anonymous:    true
            logout:
                target: /login






    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/index_front, role: ROLE_Etudiant }
        - { path: ^/index_front, role: ROLE_Parent }
        - { path: ^/index, role: ROLE_Professeur }
        - { path: ^/index, role: ROLE_Scolarite }

