bibliotheque_homepage:
    path:     /
    defaults: { _controller: BibliothequeBundle:Default:index }
biblio_catalogue:
    path:     /gestion_catalogue
    defaults: { _controller: BibliothequeBundle:Default:index }
biblio_emprunt:
    path:     /back/emprunts
    defaults: { _controller: BibliothequeBundle:Emprunt:view }
emprunt:
    path:     /back/emprunts/{id}
    defaults: { _controller: BibliothequeBundle:Emprunt:viewEmprunt }
biblio_emprunt_categorie:
    path:     /back/emprunts/categorie/{categorie}
    defaults: { _controller: BibliothequeBundle:Emprunt:viewByCategorie }
biblio_emprunt_livre:
    path:     /back/emprunts/livre/{categorie}
    defaults: { _controller: BibliothequeBundle:Emprunt:viewByLivre }
edit_emprunt:
    path:     /back/emprunts/edit/{id}/{choix}
    defaults: { _controller: BibliothequeBundle:Emprunt:edit }
    options:
        expose: true
biblio_reservation:
    path:     /gestion_reservation
    defaults: { _controller: BibliothequeBundle:Default:index }
biblio_catalogue_front:
    path:     /catalogue
    defaults: { _controller: BibliothequeBundle:Default:index }
biblio_emprunt_front:
    path:     /front/emprunts
    defaults: { _controller: BibliothequeBundle:Emprunt:viewFront }
emprunt_front:
    path:     /front/emprunts/{id}
    defaults: { _controller: BibliothequeBundle:Emprunt:viewFrontEmprunt }
biblio_emprunt_front_categorie:
    path:     /front/emprunts/{categorie}
    defaults: { _controller: BibliothequeBundle:Emprunt:viewFrontByCategorie }
biblio_emprunt_front_livre:
    path:     /front/emprunts/livre/{categorie}
    defaults: { _controller: BibliothequeBundle:Emprunt:viewFrontByLivre }
biblio_reservation_front:
    path:     /reservation
    defaults: { _controller: BibliothequeBundle:Default:index }
add_livre:
    path:     /back/add
    defaults: { _controller: BibliothequeBundle:Catalogue:add }

edit_livre:
    path:     /back/edit/{id}
    defaults: { _controller: BibliothequeBundle:Catalogue:edit }

delete_livre:
    path:     /back/delete/{id}
    defaults: { _controller: BibliothequeBundle:Catalogue:delete }
    options:
        expose: true

catalogue_livre:
    path:     /back/catalogue
    defaults: { _controller: BibliothequeBundle:Catalogue:search }

catalogue_livre_front:
    path:     /front/catalogue
    defaults: { _controller: BibliothequeBundle:Catalogue:catalogue }
emprunter:
    path:     /front/emprunter
    defaults: { _controller: BibliothequeBundle:Emprunt:add }

delete_emprunt:
    path:     /annuler/{id}
    defaults: { _controller: BibliothequeBundle:Emprunt:delete }
    options:
        expose: true
