bibliotheque_homepage:
    path:     /
    defaults: { _controller: BibliothequeBundle:Default:index }
biblio_catalogue:
    path:     /gestion_catalogue
    defaults: { _controller: BibliothequeBundle:Default:index }
biblio_emprunt:
    path:     /back/emprunts
    defaults: { _controller: BibliothequeBundle:Emprunt:view }
emprunt:
    path:     /back/emprunts/{id}
    defaults: { _controller: BibliothequeBundle:Emprunt:viewEmprunt }
biblio_emprunt_categorie:
    path:     /back/emprunts/categorie/{categorie}
    defaults: { _controller: BibliothequeBundle:Emprunt:viewByCategorie }
biblio_emprunt_livre:
    path:     /back/emprunts/livre/{categorie}
    defaults: { _controller: BibliothequeBundle:Emprunt:viewByLivre }
edit_emprunt:
    path:     /back/emprunts/edit/{id}/{choix}
    defaults: { _controller: BibliothequeBundle:Emprunt:edit }
    options:
        expose: true
biblio_reservation:
    path:     /gestion_reservation
    defaults: { _controller: BibliothequeBundle:Default:index }
biblio_catalogue_front:
    path:     /catalogue
    defaults: { _controller: BibliothequeBundle:Default:index }
biblio_emprunt_front:
    path:     /front/emprunts
    defaults: { _controller: BibliothequeBundle:Emprunt:viewFront }
emprunt_front:
    path:     /front/emprunts/{id}
    defaults: { _controller: BibliothequeBundle:Emprunt:viewFrontEmprunt }
biblio_emprunt_front_categorie:
    path:     /front/emprunts/{categorie}
    defaults: { _controller: BibliothequeBundle:Emprunt:viewFrontByCategorie }
biblio_emprunt_front_livre:
    path:     /front/emprunts/livre/{categorie}
    defaults: { _controller: BibliothequeBundle:Emprunt:viewFrontByLivre }

rechercher_empruntFront:
    path:     /front/emprunt/rechercher
    defaults: { _controller: BibliothequeBundle:Emprunt:rechercher_empruntFront }

biblio_reservation_front:
    path:     /reservationphp
    defaults: { _controller: BibliothequeBundle:Default:index }
add_livre:
    path:     /back/add
    defaults: { _controller: BibliothequeBundle:Catalogue:add }

edit_livre:
    path:     /back/edit/{id}
    defaults: { _controller: BibliothequeBundle:Catalogue:edit }

delete_livre:
    path:     /back/delete/{id}
    defaults: { _controller: BibliothequeBundle:Catalogue:delete }
    options:
        expose: true

catalogue_livre:
    path:     /back/catalogue
    defaults: { _controller: BibliothequeBundle:Catalogue:search }

catalogue_livre_front:
    path:     /front/catalogue
    defaults: { _controller: BibliothequeBundle:Catalogue:catalogue }

catalogue_livre_front_categorie:
    path:     /front/Catalogue/{categorie}
    defaults: { _controller: BibliothequeBundle:Catalogue:catalogue_livre_front_categorie }

rechercher_livre:
    path:     /front/catalogue/rechercher
    defaults: { _controller: BibliothequeBundle:Catalogue:rechercher_livre }

emprunter:
    path:     /front/emprunter
    defaults: { _controller: BibliothequeBundle:Emprunt:add }

delete_emprunt:
    path:     /annuler/{id}
    defaults: { _controller: BibliothequeBundle:Emprunt:delete }
    options:
        expose: true

planning:
    path:     /front/planning
    defaults: { _controller: BibliothequeBundle:Emprunt:planning }

mcatalogue_back:
    path:     /mobile/back/livres/{iduser}
    defaults: { _controller: BibliothequeBundle:Catalogue:list_livres_by_bibliothecaire }

medit_livre:
    path:     /mobile/back/livre/edit/{id}/{titre}/{auteur}/{editeur}/{categorie}/{taille}/{quantite}
    defaults: { _controller: BibliothequeBundle:Catalogue:Medit }

mdelete_livre:
    path:     /mobile/back/livre/delete/{id}
    defaults: { _controller: BibliothequeBundle:Catalogue:delete }

mList_Biblio:
    path:     /mobile/front/biblios
    defaults: { _controller: BibliothequeBundle:Catalogue:list_biblios }

mcatalogue_front:
    path:     /mobile/front/livres/{idbibliotheque}
    defaults: { _controller: BibliothequeBundle:Catalogue:list_livres_by_biblio }

Memprunter:
    path:     /mobile/front/emprunter/{idemprunteur}/{idlivre}/{datedebut}/{datefin}
    defaults: { _controller: BibliothequeBundle:Emprunt:Emprunter }

Mview_emprunts:
    path:     /mobile/front/emprunts/{iduser}
    defaults: { _controller: BibliothequeBundle:Emprunt:MviewFrontEmprunt }

Mlist_livre:
    path:     /mobile/front/livres
    defaults: { _controller: BibliothequeBundle:Catalogue:list_livres }