bibliotheque_homepage:
    path:     /
    defaults: { _controller: BibliothequeBundle:Default:index }
biblio_catalogue:
    path:     /gestion_catalogue
    defaults: { _controller: BibliothequeBundle:Default:index }
biblio_emprunt:
    path:     /back/emprunts
    defaults: { _controller: BibliothequeBundle:Emprunt:view }
edit_emprunt:
    path:     /back/emprunts/edit/{id}/{choix}
    defaults: { _controller: BibliothequeBundle:Emprunt:edit }
    options:
        expose: true
biblio_reservation:
    path:     /gestion_reservation
    defaults: { _controller: BibliothequeBundle:Default:index }
biblio_catalogue_front:
    path:     /catalogue
    defaults: { _controller: BibliothequeBundle:Default:index }
biblio_emprunt_front:
    path:     /emprunt
    defaults: { _controller: BibliothequeBundle:Default:index }
biblio_reservation_front:
    path:     /reservation
    defaults: { _controller: BibliothequeBundle:Default:index }
add_livre:
    path:     /back/add
    defaults: { _controller: BibliothequeBundle:Catalogue:add }

edit_livre:
    path:     /back/edit/{id}
    defaults: { _controller: BibliothequeBundle:Catalogue:edit }

delete_livre:
    path:     /back/delete/{id}
    defaults: { _controller: BibliothequeBundle:Catalogue:delete }
    options:
        expose: true

catalogue_livre:
    path:     /back/catalogue
    defaults: { _controller: BibliothequeBundle:Catalogue:search }

catalogue_livre_front:
    path:     /front/catalogue
    defaults: { _controller: BibliothequeBundle:Catalogue:catalogue }
emprunter:
    path:     /front/emprunter
    defaults: { _controller: BibliothequeBundle:Emprunt:add }

delete:
    path:     /annuler
    defaults: { _controller: BibliothequeBundle:Emprunt:delete }
