user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
front:
    path:     /front
    defaults: { _controller: SchoolBundle:Default:front }
back:
    path:     /back
    defaults: { _controller: SchoolBundle:Default:back }
login:
    path:     /mobile/login/{username}/{pwd}
    defaults: { _controller: UserBundle:Default:login }